/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var unicode = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,5],$V1=[1,6],$V2=[1,7],$V3=[1,12],$V4=[1,14],$V5=[1,15],$V6=[37,38,57],$V7=[52,53],$V8=[5,37,54,55,56];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"expressions":3,"relation":4,"EOF":5,"object":6,"OBJ":7,"THIS":8,"THAT":9,"attribute":10,"SIZE":11,"HEIGHT":12,"WIDTH":13,"COLOR":14,"TEXT":15,"HORILOC":16,"VERTILOC":17,"LOC":18,"doubleAttribute":19,"HORIDIST":20,"VERTIDIST":21,"DISTANCE":22,"adverb":23,"DEEP":24,"一点":25,"SHALLOW":26,"BIG":27,"SMALL":28,"direction":29,"LEFT":30,"RIGHT":31,"UP":32,"DOWN":33,"location":34,"HERE":35,"THERE":36,"D":37,"AND":38,"MIDDLE":39,"const":40,"ONE":41,"TWO":42,"THREE":43,"FOUR":44,"FIVE":45,"SIX":46,"SEVEN":47,"EIGHT":48,"NINE":49,"TEN":50,"value":51,"TIME":52,"FRACTION":53,"EQUAL":54,"LEQ":55,"GEQ":56,"AT":57,"predicate":58,"NEW":59,"MOVE":60,"CHANGE":61,"target":62,"adverbial":63,"DAO":64,"WANG":65,"IS":66,"conditions":67,"ALSO":68,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"OBJ",8:"THIS",9:"THAT",11:"SIZE",12:"HEIGHT",13:"WIDTH",14:"COLOR",15:"TEXT",16:"HORILOC",17:"VERTILOC",18:"LOC",20:"HORIDIST",21:"VERTIDIST",22:"DISTANCE",24:"DEEP",25:"一点",26:"SHALLOW",27:"BIG",28:"SMALL",30:"LEFT",31:"RIGHT",32:"UP",33:"DOWN",35:"HERE",36:"THERE",37:"D",38:"AND",39:"MIDDLE",41:"ONE",42:"TWO",43:"THREE",44:"FOUR",45:"FIVE",46:"SIX",47:"SEVEN",48:"EIGHT",49:"NINE",50:"TEN",52:"TIME",53:"FRACTION",54:"EQUAL",55:"LEQ",56:"GEQ",57:"AT",59:"NEW",60:"MOVE",61:"CHANGE",64:"DAO",65:"WANG",66:"IS",68:"ALSO"},
productions_: [0,[3,2],[6,1],[6,1],[6,1],[6,2],[6,2],[10,1],[10,1],[10,1],[10,1],[10,1],[10,1],[10,1],[10,1],[19,1],[19,1],[19,1],[23,2],[23,2],[23,2],[23,2],[29,1],[29,1],[29,1],[29,1],[34,1],[34,1],[34,3],[34,5],[40,1],[40,1],[40,1],[40,1],[40,1],[40,1],[40,1],[40,1],[40,1],[40,1],[51,4],[51,4],[51,3],[51,5],[4,3],[4,3],[4,3],[4,5],[58,1],[58,1],[58,1],[62,1],[62,3],[62,5],[63,2],[63,2],[63,2],[63,2],[67,3],[67,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 console.log($$[$0-1]);
        //   console.log($$[$0]);
        //   console.log($$[$01]);
        //   console.log($$[$02]);
          return {"predicate": $$[$0-1]}; 
break;
case 2:
this.$ = {"name": $$[$0], "type": "obj"};
break;
case 3: case 4: case 5: case 6:
this.$ = {"name": $$[$0], "type": "ref"};
break;
case 7:
this.$ = "size"
break;
case 8:
this.$ = "height"
break;
case 9:
this.$ = "width"
break;
case 10:
this.$ = "color"
break;
case 11:
this.$ = "text"
break;
case 12:
this.$ = "horiloc"
break;
case 13:
this.$ = "vertiloc"
break;
case 14:
this.$ = "loc"
break;
case 15:
this.$ = "horidist"
break;
case 16:
this.$ = "vertidist"
break;
case 17:
this.$ = "dist"
break;
case 18:
this.$ = "deep"
break;
case 19:
this.$ = "shallow"
break;
case 20:
this.$ = "big"
break;
case 21:
this.$ = "small"
break;
case 22:
this.$ = "left"
break;
case 23:
this.$ = "right"
break;
case 24:
this.$ = "up"
break;
case 25:
this.$ = "down"
break;
case 26:
this.$ = {"loc": "here", "type": "ref"}
break;
case 27:
this.$ = {"loc": "there", "type": "ref"}
break;
case 28:
this.$ = {"obj": $$[$0-2], "type": "single", "direction": $$[$0]}
break;
case 29:
this.$ = {"obj_1": $$[$0-4], "obj_2": $$[$0-2], "type": "double", "loc": "middle"}
break;
case 30:
this.$ = 1
break;
case 31:
this.$ = 2
break;
case 32:
this.$ = 3
break;
case 33:
this.$ = 4
break;
case 34:
this.$ = 5
break;
case 35:
this.$ = 6
break;
case 36:
this.$ = 7
break;
case 37:
this.$ = 8
break;
case 38:
this.$ = 9
break;
case 39:
this.$ = 10
break;
case 40:
this.$ = {"val": $$[$0-3], "const": $$[$0-1], "type": "time"};
break;
case 41:
this.$ = {"val": $$[$0-3], "const": $$[$0-1], "type": "fraction"};
break;
case 42: case 52:
this.$ = {"obj": $$[$0-2], "type": "single", "val": $$[$0]};
break;
case 43: case 53:
this.$ = {"obj_1": $$[$0-4], "obj_2": $$[$0-2], "type": "double", "val": $$[$0]};
break;
case 44:
this.$ = {"type": "equation", "val_1": $$[$0-2], "val_2": $$[$0], "op": "="};
break;
case 45:
this.$ = {"type": "equation", "val_1": $$[$0-2], "val_2": $$[$0], "op": "<"};
break;
case 46:
this.$ = {"type": "equation", "val_1": $$[$0-2], "val_2": $$[$0], "op": ">"};
break;
case 47:
this.$ = {"type": "direction", "obj_1": $$[$0-4], "obj_1": $$[$0-2], "direction": $$[$0]};
break;
case 48:
this.$ = "new";
break;
case 49:
this.$ = "move";
break;
case 50:
this.$ = "change";
break;
case 51:
this.$ = {"obj": $$[$0], "type": "single", "val": "loc"};
break;
case 54: case 55:
this.$ = {"type": "loc", "loc": $$[$0]};
break;
case 56:
this.$ = {"type": "direction", "direction": $$[$0]};
break;
case 57:
this.$ = {"type": "value", "value": $$[$0]};
break;
case 58:
 this.$ = $$[$0-2]; 
break;
case 59:
 this.$ = $$[$0]; 
break;
}
},
table: [{3:1,4:2,6:4,7:$V0,8:$V1,9:$V2,51:3},{1:[3]},{5:[1,8]},{37:$V3,54:[1,9],55:[1,10],56:[1,11]},{37:$V4,38:$V5,57:[1,13]},o($V6,[2,2]),o($V6,[2,3],{7:[1,16]}),o($V6,[2,4],{7:[1,17]}),{1:[2,1]},{6:19,7:$V0,8:$V1,9:$V2,51:18},{6:19,7:$V0,8:$V1,9:$V2,51:20},{6:19,7:$V0,8:$V1,9:$V2,51:21},{40:22,41:[1,23],42:[1,24],43:[1,25],44:[1,26],45:[1,27],46:[1,28],47:[1,29],48:[1,30],49:[1,31],50:[1,32]},{6:33,7:$V0,8:$V1,9:$V2},{10:34,11:[1,35],12:[1,36],13:[1,37],14:[1,38],15:[1,39],16:[1,40],17:[1,41],18:[1,42]},{6:43,7:$V0,8:$V1,9:$V2},o($V6,[2,5]),o($V6,[2,6]),{5:[2,44],37:$V3},{37:$V4,38:$V5},{5:[2,45],37:$V3},{5:[2,46],37:$V3},{52:[1,44],53:[1,45]},o($V7,[2,30]),o($V7,[2,31]),o($V7,[2,32]),o($V7,[2,33]),o($V7,[2,34]),o($V7,[2,35]),o($V7,[2,36]),o($V7,[2,37]),o($V7,[2,38]),o($V7,[2,39]),{37:[1,46]},o($V8,[2,42]),o($V8,[2,7]),o($V8,[2,8]),o($V8,[2,9]),o($V8,[2,10]),o($V8,[2,11]),o($V8,[2,12]),o($V8,[2,13]),o($V8,[2,14]),{37:[1,47]},o($V8,[2,40]),o($V8,[2,41]),{29:48,30:[1,49],31:[1,50],32:[1,51],33:[1,52]},{19:53,20:[1,54],21:[1,55],22:[1,56]},{5:[2,47]},{5:[2,22]},{5:[2,23]},{5:[2,24]},{5:[2,25]},o($V8,[2,43]),o($V8,[2,15]),o($V8,[2,16]),o($V8,[2,17])],
defaultActions: {8:[2,1],48:[2,47],49:[2,22],50:[2,23],51:[2,24],52:[2,25]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 59
break;
case 2:return 60
break;
case 3:return 61
break;
case 4:return 8
break;
case 5:return 9
break;
case 6:return 35
break;
case 7:return 36
break;
case 8:return 11
break;
case 9:return 12
break;
case 10:return 13
break;
case 11:return 14
break;
case 12:return 15
break;
case 13:return 16
break;
case 14:return 17
break;
case 15:return 18
break;
case 16:return 20
break;
case 17:return 21
break;
case 18:return 22
break;
case 19:return 24
break;
case 20:return 26
break;
case 21:return 27
break;
case 22:return 28
break;
case 23:return 30
break;
case 24:return 31
break;
case 25:return 32
break;
case 26:return 33
break;
case 27:return 30
break;
case 28:return 31
break;
case 29:return 32
break;
case 30:return 33 
break;
case 31:return 39 
break;
case 32:return 37
break;
case 33:return 38
break;
case 34:return 64
break;
case 35:return 57
break;
case 36:return 65
break;
case 37:return 66
break;
case 38:return 52
break;
case 39:return 'DIFF'
break;
case 40:return 'FOR'
break;
case 41:return 'FOR'
break;
case 42:return 68
break;
case 43:return 7
break;
case 44:return 'BIT'
break;
case 45:return 53
break;
case 46:return 41
break;
case 47:return 42
break;
case 48:return 43
break;
case 49:return 44
break;
case 50:return 45
break;
case 51:return 46
break;
case 52:return 47
break;
case 53:return 48
break;
case 54:return 49
break;
case 55:return 50
break;
case 56:return 54
break;
case 57:return 56
break;
case 58:return 55
break;
case 59:return 5
break;
case 60:return 'INVALID'
break;
}
},
rules: [/^(?:\s+)/,/^(?:新建)/,/^(?:移动)/,/^(?:修改)/,/^(?:这个)/,/^(?:那个)/,/^(?:这里)/,/^(?:那里)/,/^(?:大小)/,/^(?:高度)/,/^(?:宽度)/,/^(?:颜色)/,/^(?:文字)/,/^(?:水平位置)/,/^(?:竖直位置)/,/^(?:位置)/,/^(?:水平距离)/,/^(?:竖直距离)/,/^(?:距离)/,/^(?:深)/,/^(?:浅)/,/^(?:大)/,/^(?:小)/,/^(?:左边)/,/^(?:右边)/,/^(?:上边)/,/^(?:下边)/,/^(?:左方)/,/^(?:右方)/,/^(?:上方)/,/^(?:下方)/,/^(?:中点)/,/^(?:的)/,/^(?:和)/,/^(?:到)/,/^(?:在)/,/^(?:往)/,/^(?:为)/,/^(?:倍)/,/^(?:差)/,/^(?:使得)/,/^(?:使)/,/^(?:且)/,/^(?:[\u4e00-\u9fa5A-Za-z]+?(?=[和的到在为深浅大小]))/,/^(?:一点)/,/^(?:分之一)/,/^(?:一)/,/^(?:二)/,/^(?:三)/,/^(?:四)/,/^(?:五)/,/^(?:六)/,/^(?:七)/,/^(?:八)/,/^(?:九)/,/^(?:十)/,/^(?:等于)/,/^(?:大于)/,/^(?:小于)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = unicode;
exports.Parser = unicode.Parser;
exports.parse = function () { return unicode.parse.apply(unicode, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}