/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var unicode = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[1,9],$V2=[1,10],$V3=[10,11,12],$V4=[60,61,62,63],$V5=[40,41,60,61,62,63],$V6=[1,23],$V7=[1,24],$V8=[1,28],$V9=[1,29],$Va=[1,30],$Vb=[1,31],$Vc=[1,35],$Vd=[1,36],$Ve=[1,37],$Vf=[1,38],$Vg=[1,39],$Vh=[1,40],$Vi=[1,41],$Vj=[1,42],$Vk=[40,60,61,62,63,64],$Vl=[1,67],$Vm=[1,68],$Vn=[1,69],$Vo=[55,56],$Vp=[40,64];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"expressions":3,"predicate":4,"target":5,"adverbial":6,"conditions":7,"EOF":8,"object":9,"OBJ":10,"THIS":11,"THAT":12,"attribute":13,"SIZE":14,"HEIGHT":15,"WIDTH":16,"COLOR":17,"TEXT":18,"HORILOC":19,"VERTILOC":20,"LOC":21,"doubleAttribute":22,"HORIDIST":23,"VERTIDIST":24,"DISTANCE":25,"adverb":26,"DEEP":27,"一点":28,"SHALLOW":29,"BIG":30,"SMALL":31,"direction":32,"LEFT":33,"RIGHT":34,"UP":35,"DOWN":36,"location":37,"HERE":38,"THERE":39,"D":40,"AND":41,"MIDDLE":42,"const":43,"ONE":44,"TWO":45,"THREE":46,"FOUR":47,"FIVE":48,"SIX":49,"SEVEN":50,"EIGHT":51,"NINE":52,"TEN":53,"value":54,"TIME":55,"FRACTION":56,"NEW":57,"MOVE":58,"CHANGE":59,"DAO":60,"AT":61,"WANG":62,"IS":63,"FOR":64,"$accept":0,"$end":1},
terminals_: {2:"error",8:"EOF",10:"OBJ",11:"THIS",12:"THAT",14:"SIZE",15:"HEIGHT",16:"WIDTH",17:"COLOR",18:"TEXT",19:"HORILOC",20:"VERTILOC",21:"LOC",23:"HORIDIST",24:"VERTIDIST",25:"DISTANCE",27:"DEEP",28:"一点",29:"SHALLOW",30:"BIG",31:"SMALL",33:"LEFT",34:"RIGHT",35:"UP",36:"DOWN",38:"HERE",39:"THERE",40:"D",41:"AND",42:"MIDDLE",44:"ONE",45:"TWO",46:"THREE",47:"FOUR",48:"FIVE",49:"SIX",50:"SEVEN",51:"EIGHT",52:"NINE",53:"TEN",55:"TIME",56:"FRACTION",57:"NEW",58:"MOVE",59:"CHANGE",60:"DAO",61:"AT",62:"WANG",63:"IS",64:"FOR"},
productions_: [0,[3,5],[9,1],[9,1],[9,1],[9,2],[9,2],[13,1],[13,1],[13,1],[13,1],[13,1],[13,1],[13,1],[13,1],[22,1],[22,1],[22,1],[26,2],[26,2],[26,2],[26,2],[32,1],[32,1],[32,1],[32,1],[37,1],[37,1],[37,3],[37,5],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[43,1],[54,4],[54,4],[54,3],[54,5],[4,1],[4,1],[4,1],[5,1],[5,3],[5,5],[6,2],[6,2],[6,2],[6,2],[7,1]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 console.log($$[$0-4]);
          console.log($$[$0-3]);
          console.log($$[$0-2]);
          console.log($$[$0-1]);
          return {"predicate": $$[$0-4]}; 
break;
case 2:
this.$ = {"name": $$[$0], "type": "obj"};
break;
case 3: case 4: case 5: case 6:
this.$ = {"name": $$[$0], "type": "ref"};
break;
case 7:
this.$ = "size"
break;
case 8:
this.$ = "height"
break;
case 9:
this.$ = "width"
break;
case 10:
this.$ = "color"
break;
case 11:
this.$ = "text"
break;
case 12:
this.$ = "horiloc"
break;
case 13:
this.$ = "vertiloc"
break;
case 14:
this.$ = "loc"
break;
case 15:
this.$ = "horidist"
break;
case 16:
this.$ = "vertidist"
break;
case 17:
this.$ = "dist"
break;
case 18:
this.$ = "deep"
break;
case 19:
this.$ = "shallow"
break;
case 20:
this.$ = "big"
break;
case 21:
this.$ = "small"
break;
case 22:
this.$ = "left"
break;
case 23:
this.$ = "right"
break;
case 24:
this.$ = "up"
break;
case 25:
this.$ = "down"
break;
case 26:
this.$ = {"loc": "here", "type": "ref"}
break;
case 27:
this.$ = {"loc": "there", "type": "ref"}
break;
case 28:
this.$ = {"obj": $$[$0-2], "type": "single", "direction": $$[$0]}
break;
case 29:
this.$ = {"obj_1": $$[$0-4], "obj_2": $$[$0-2], "type": "double", "loc": "middle"}
break;
case 30:
this.$ = 1
break;
case 31:
this.$ = 2
break;
case 32:
this.$ = 3
break;
case 33:
this.$ = 4
break;
case 34:
this.$ = 5
break;
case 35:
this.$ = 6
break;
case 36:
this.$ = 7
break;
case 37:
this.$ = 8
break;
case 38:
this.$ = 9
break;
case 39:
this.$ = 10
break;
case 40:
this.$ = {"val": $$[$0-3], "const": $$[$0-1], "type": "time"};
break;
case 41:
this.$ = {"val": $$[$0-3], "const": $$[$0-1], "type": "fraction"};
break;
case 42: case 48:
this.$ = {"obj": $$[$0-2], "type": "single", "val": $$[$0]};
break;
case 43: case 49:
this.$ = {"obj_1": $$[$0-4], "obj_2": $$[$0-2], "type": "double", "val": $$[$0]};
break;
case 44:
this.$ = "new";
break;
case 45:
this.$ = "move";
break;
case 46:
this.$ = "change";
break;
case 47:
this.$ = {"obj": $$[$0], "type": "single", "val": "loc"};
break;
case 50: case 51:
this.$ = {"type": "loc", "loc": $$[$0]};
break;
case 52:
this.$ = {"type": "direction", "direction": $$[$0]};
break;
case 53:
this.$ = {"type": "value", "value": $$[$0]};
break;
case 54:
 this.$ = $$[$0]; 
break;
}
},
table: [{3:1,4:2,57:[1,3],58:[1,4],59:[1,5]},{1:[3]},{5:6,9:7,10:$V0,11:$V1,12:$V2},o($V3,[2,44]),o($V3,[2,45]),o($V3,[2,46]),{6:11,60:[1,12],61:[1,13],62:[1,14],63:[1,15]},o($V4,[2,47],{40:[1,16],41:[1,17]}),o($V5,[2,2]),o($V5,[2,3],{10:[1,18]}),o($V5,[2,4],{10:[1,19]}),{7:20,64:[1,21]},{9:25,10:$V0,11:$V1,12:$V2,37:22,38:$V6,39:$V7},{9:25,10:$V0,11:$V1,12:$V2,37:26,38:$V6,39:$V7},{32:27,33:$V8,34:$V9,35:$Va,36:$Vb},{9:33,10:$V0,11:$V1,12:$V2,54:32},{13:34,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh,20:$Vi,21:$Vj},{9:43,10:$V0,11:$V1,12:$V2},o($V5,[2,5]),o($V5,[2,6]),{8:[1,44]},{8:[2,54]},{64:[2,50]},{64:[2,26]},{64:[2,27]},{40:[1,45],41:[1,46]},{64:[2,51]},{64:[2,52]},{64:[2,22]},{64:[2,23]},{64:[2,24]},{64:[2,25]},{40:[1,47],64:[2,53]},{40:[1,48],41:[1,49]},o($V4,[2,48]),o($Vk,[2,7]),o($Vk,[2,8]),o($Vk,[2,9]),o($Vk,[2,10]),o($Vk,[2,11]),o($Vk,[2,12]),o($Vk,[2,13]),o($Vk,[2,14]),{40:[1,50]},{1:[2,1]},{32:51,33:$V8,34:$V9,35:$Va,36:$Vb},{9:52,10:$V0,11:$V1,12:$V2},{43:53,44:[1,54],45:[1,55],46:[1,56],47:[1,57],48:[1,58],49:[1,59],50:[1,60],51:[1,61],52:[1,62],53:[1,63]},{13:64,14:$Vc,15:$Vd,16:$Ve,17:$Vf,18:$Vg,19:$Vh,20:$Vi,21:$Vj},{9:65,10:$V0,11:$V1,12:$V2},{22:66,23:$Vl,24:$Vm,25:$Vn},{64:[2,28]},{40:[1,70]},{55:[1,71],56:[1,72]},o($Vo,[2,30]),o($Vo,[2,31]),o($Vo,[2,32]),o($Vo,[2,33]),o($Vo,[2,34]),o($Vo,[2,35]),o($Vo,[2,36]),o($Vo,[2,37]),o($Vo,[2,38]),o($Vo,[2,39]),o($Vp,[2,42]),{40:[1,73]},o($V4,[2,49]),o($Vk,[2,15]),o($Vk,[2,16]),o($Vk,[2,17]),{42:[1,74]},o($Vp,[2,40]),o($Vp,[2,41]),{22:75,23:$Vl,24:$Vm,25:$Vn},{64:[2,29]},o($Vp,[2,43])],
defaultActions: {21:[2,54],22:[2,50],23:[2,26],24:[2,27],26:[2,51],27:[2,52],28:[2,22],29:[2,23],30:[2,24],31:[2,25],44:[2,1],51:[2,28],74:[2,29]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 57
break;
case 2:return 58
break;
case 3:return 59
break;
case 4:return 11
break;
case 5:return 12
break;
case 6:return 38
break;
case 7:return 39
break;
case 8:return 14
break;
case 9:return 15
break;
case 10:return 16
break;
case 11:return 17
break;
case 12:return 18
break;
case 13:return 19
break;
case 14:return 20
break;
case 15:return 21
break;
case 16:return 23
break;
case 17:return 24
break;
case 18:return 25
break;
case 19:return 27
break;
case 20:return 29
break;
case 21:return 30
break;
case 22:return 31
break;
case 23:return 33
break;
case 24:return 34
break;
case 25:return 35
break;
case 26:return 36
break;
case 27:return 33
break;
case 28:return 34
break;
case 29:return 35
break;
case 30:return 36 
break;
case 31:return 42 
break;
case 32:return 40
break;
case 33:return 41
break;
case 34:return 60
break;
case 35:return 61
break;
case 36:return 62
break;
case 37:return 63
break;
case 38:return 55
break;
case 39:return 'DIFF'
break;
case 40:return 64
break;
case 41:return 64
break;
case 42:return 10
break;
case 43:return 56
break;
case 44:return 44
break;
case 45:return 45
break;
case 46:return 46
break;
case 47:return 47
break;
case 48:return 48
break;
case 49:return 49
break;
case 50:return 50
break;
case 51:return 51
break;
case 52:return 52
break;
case 53:return 53
break;
case 54:return 8
break;
case 55:return 'INVALID'
break;
}
},
rules: [/^(?:\s+)/,/^(?:新建)/,/^(?:移动)/,/^(?:修改)/,/^(?:这个)/,/^(?:那个)/,/^(?:这里)/,/^(?:那里)/,/^(?:大小)/,/^(?:高度)/,/^(?:宽度)/,/^(?:颜色)/,/^(?:文字)/,/^(?:水平位置)/,/^(?:竖直位置)/,/^(?:位置)/,/^(?:水平距离)/,/^(?:竖直距离)/,/^(?:距离)/,/^(?:深)/,/^(?:浅)/,/^(?:大)/,/^(?:小)/,/^(?:左边)/,/^(?:右边)/,/^(?:上边)/,/^(?:下边)/,/^(?:左方)/,/^(?:右方)/,/^(?:上方)/,/^(?:下方)/,/^(?:中点)/,/^(?:的)/,/^(?:和)/,/^(?:到)/,/^(?:在)/,/^(?:往)/,/^(?:为)/,/^(?:倍)/,/^(?:差)/,/^(?:使得)/,/^(?:使)/,/^(?:[\u4e00-\u9fa5]+?(?=[新建移动修改这那里大小高宽度颜色文字水平位置竖直距离深浅左右上下边方的和到在往为]))/,/^(?:分之一)/,/^(?:一)/,/^(?:二)/,/^(?:三)/,/^(?:四)/,/^(?:五)/,/^(?:六)/,/^(?:七)/,/^(?:八)/,/^(?:九)/,/^(?:十)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = unicode;
exports.Parser = unicode.Parser;
exports.parse = function () { return unicode.parse.apply(unicode, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}